version: '2'

services:
  b-client:
    build: client
    ports:
      - "7001:80"

  b-server:
    build: server
    ports:
      - "7002:7002"

  database:
    image: mongo
    volumes:
      - "/home/mue/Programming/Projects/mean-docker-setup/mongo-db:/data/db"
    ports:
      - "27018:27017"