version: '2'

services:
  client:
    build: client
    image: b-client
    expose:
     - "80"
    depends_on:
      - database
      - api

  api:
    build: api
    image: b-api
    expose:
      - "7002"
    depends_on:
      - database

  database:
    image: mongo
    expose:
      - "27017"

  reverse:
    build: reverse
    image: b-reverse
    volumes:
      - "D:/Projects/Experiments/mean-docker-setup/reverse_logs:/var/log/nginx"
    depends_on:
      - database
      - client
      - api
    ports:
      - "8070:8070"