version: '2'

services:
  client:
    build: client
    restart: always
    image: b-client
    depends_on:
      - database
      - api

  api:
    build: api
    image: b-api
    restart: always
    depends_on:
      - database

  database:
    restart: always
    image: mongo

  reverse:
    build: reverse
    image: b-reverse
    restart: always
    volumes:
      - "D:/Projects/Experiments/mean-docker-setup/reverse_logs:/var/log/nginx"
    depends_on:
      - database
      - client
      - api
    ports:
      - "8070:8070"