version: '2'

services:
  client:
    restart: always
    image: b-client
    depends_on:
      - database
      - api

  api:
    image: b-api
    restart: always
    depends_on:
      - database

  database:
    restart: always
    image: mongo

  reverse:
    image: b-reverse
    restart: always
    depends_on:
      - database
      - client
      - api
    ports:
      - "80:8070"